version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - db
  db:
    image: pg_render_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql